/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */









//  import React from 'react';
//  import { StyleSheet, Button, View, SafeAreaView, Text, Alert } from 'react-native';
 
//  const Separator = () => (
//    <View style={styles.separator} />
//  );
 
//  const App = () => (
//    <SafeAreaView style={styles.container}>
//      <View>
//        <Text style={styles.title}>
//          The title and onPress handler are required. It is recommended to set accessibilityLabel to help make your app usable by everyone.
//        </Text>
//        <Button
//          title="Press me"
//          onPress={() => Alert.alert('Simple Button pressed')}
//        />
//      </View>
//      <Separator />
//      <View>
//        <Text style={styles.title}>
//          Adjust the color in a way that looks standard on each platform. On  iOS, the color prop controls the color of the text. On Android, the color adjusts the background color of the button.
//        </Text>
//        <Button
//          title="Press me"
//          color="#f194ff"
//          onPress={() => Alert.alert('Button with adjusted color pressed')}
//        />
//      </View>
//      <Separator />
//      <View>
//        <Text style={styles.title}>
//          All interaction for the component are disabled.
//        </Text>
//        <Button
//          title="Press me"
//          disabled
//          onPress={() => Alert.alert('Cannot press this one')}
//        />
//      </View>
//      <Separator />
//      <View>
//        <Text style={styles.title}>
//          This layout strategy lets the title define the width of the button.
//        </Text>
//        <View style={styles.fixToText}>
//          <Button
//            title="Left button"
//            onPress={() => Alert.alert('Left button pressed')}
//          />
//          <Button
//            title="Right button"
//            onPress={() => Alert.alert('Right button pressed')}
//          />
//        </View>
//      </View>
//    </SafeAreaView>
//  );
 
//  const styles = StyleSheet.create({
//    container: {
//      flex: 1,
//      justifyContent: 'center',
//      marginHorizontal: 16,
//    },
//    title: {
//      textAlign: 'center',
//      marginVertical: 8,
//    },
//    fixToText: {
//      flexDirection: 'row',
//      justifyContent: 'space-between',
//    },
//    separator: {
//      marginVertical: 8,
//      borderBottomColor: '#737373',
//      borderBottomWidth: StyleSheet.hairlineWidth,
//    },
//  });
 
//  export default App;





import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View ,Button,Alert,NativeModules,SafeAreaView } from 'react-native';
// import Card91Sdk from 'react-native-card91-sdk';s
import Card91Sdk from './Card91SDK'

const { SwiftComponentManager } = NativeModules;


// import React from 'react';
// import { StyleSheet, Button, View, SafeAreaView, Text, NativeModules, Alert } from 'react-native';


//const { SwiftComponentManager } = NativeModules

//const { SwiftComponentManager } = NativeModules;



//  import React, { Component } from 'react';
//  import { Platform, StyleSheet, Text, View } from 'react-native';
//  // import Card91Sdk from 'react-native-card91-sdk';s
//  import Card91Sdk from './Card91SDK'
 
 export default class App extends Component<{}> {
   render() {
     return (
       <View style={styles.container}>
         <Text style={styles.welcome}>☆Card91Sdk example☆</Text>
         <Text style={styles.instructions}>STATUS: loaded</Text>
         <Text style={styles.welcome}>☆☆☆</Text>

        

      <Button
          title="iOS SDK"
          //onPress={() => Alert.alert('Left button pressed')}

          onPress={
            () => SwiftComponentManager.open({message: 'Bridge with Swift Dev.to Tutorial'})}


        />


         <Card91Sdk />
       </View>
     );
   }
 }
 
 const styles = StyleSheet.create({
   container: {
     flex: 1,
     justifyContent: 'center',
     alignItems: 'center',
     backgroundColor: '#F5FCFF',
   },
   welcome: {
     fontSize: 20,
     textAlign: 'center',
     margin: 10,
   },
   instructions: {
     textAlign: 'center',
     color: '#333333',
     marginBottom: 5,
   },
 });
 