/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';

import {Button, NativeModules, StyleSheet, Text, View} from 'react-native';

export default class App extends Component<{}> {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆React Native Kissht Sdk example☆</Text>
        <Text style={styles.instructions}>STATUS: loaded</Text>
        <Text style={styles.welcome}>☆☆☆</Text>
        <Button
          onPress={() => {
            try {
              let params = JSON.stringify({
                mobileNumber: '919876543213',
                deviceId: 'test_device_id',
                environment: 'DEV',
                sdkAuth: 'test_sdk_auth',
              });
              NativeModules.ActivityStarter.navigateToCustomerSDK(params);
            } catch (error) {
              console.log(error);
            }
          }}
          title="Open SDK"
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
